export const CATEGORIES_ACTION_TYPES = {
  FETCH_CATEGORIES_START: "FECT_CATEGORIES_START",
  FETCH_CATEGORIES_SUCCESS: "FECT_CATEGORIES_SUCCESS",
  FETCH_CATEGORIES_FAILED: "FECT_CATEGORIES_FAILED",
};
