export const CATEGORIES_ACTION_TYPES = {
  SET_CATEGORIES_MAP: "categories/SET_CATEGORIES_MAP",
  SET_CATEGORIES_IS_LOADING: "categories/IS_LOADING",
  SET_CATEGORIES_FAILED: "categories/SET_CATEGORIES_FAILED",
};
